// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.29.0
// source: ui.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Action int32

const (
	Action_NONE                 Action = 0
	Action_LOAD_FIREWALL        Action = 1
	Action_UNLOAD_FIREWALL      Action = 2
	Action_CHANGE_CONFIG        Action = 3
	Action_ENABLE_RULE          Action = 4
	Action_DISABLE_RULE         Action = 5
	Action_DELETE_RULE          Action = 6
	Action_CHANGE_RULE          Action = 7
	Action_LOG_LEVEL            Action = 8
	Action_STOP                 Action = 9
	Action_MONITOR_PROCESS      Action = 10
	Action_STOP_MONITOR_PROCESS Action = 11
)

// Enum value maps for Action.
var (
	Action_name = map[int32]string{
		0:  "NONE",
		1:  "LOAD_FIREWALL",
		2:  "UNLOAD_FIREWALL",
		3:  "CHANGE_CONFIG",
		4:  "ENABLE_RULE",
		5:  "DISABLE_RULE",
		6:  "DELETE_RULE",
		7:  "CHANGE_RULE",
		8:  "LOG_LEVEL",
		9:  "STOP",
		10: "MONITOR_PROCESS",
		11: "STOP_MONITOR_PROCESS",
	}
	Action_value = map[string]int32{
		"NONE":                 0,
		"LOAD_FIREWALL":        1,
		"UNLOAD_FIREWALL":      2,
		"CHANGE_CONFIG":        3,
		"ENABLE_RULE":          4,
		"DISABLE_RULE":         5,
		"DELETE_RULE":          6,
		"CHANGE_RULE":          7,
		"LOG_LEVEL":            8,
		"STOP":                 9,
		"MONITOR_PROCESS":      10,
		"STOP_MONITOR_PROCESS": 11,
	}
)

func (x Action) Enum() *Action {
	p := new(Action)
	*p = x
	return p
}

func (x Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Action) Descriptor() protoreflect.EnumDescriptor {
	return file_ui_proto_enumTypes[0].Descriptor()
}

func (Action) Type() protoreflect.EnumType {
	return &file_ui_proto_enumTypes[0]
}

func (x Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Action.Descriptor instead.
func (Action) EnumDescriptor() ([]byte, []int) {
	return file_ui_proto_rawDescGZIP(), []int{0}
}

type NotificationReplyCode int32

const (
	NotificationReplyCode_OK    NotificationReplyCode = 0
	NotificationReplyCode_ERROR NotificationReplyCode = 1
)

// Enum value maps for NotificationReplyCode.
var (
	NotificationReplyCode_name = map[int32]string{
		0: "OK",
		1: "ERROR",
	}
	NotificationReplyCode_value = map[string]int32{
		"OK":    0,
		"ERROR": 1,
	}
)

func (x NotificationReplyCode) Enum() *NotificationReplyCode {
	p := new(NotificationReplyCode)
	*p = x
	return p
}

func (x NotificationReplyCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NotificationReplyCode) Descriptor() protoreflect.EnumDescriptor {
	return file_ui_proto_enumTypes[1].Descriptor()
}

func (NotificationReplyCode) Type() protoreflect.EnumType {
	return &file_ui_proto_enumTypes[1]
}

func (x NotificationReplyCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NotificationReplyCode.Descriptor instead.
func (NotificationReplyCode) EnumDescriptor() ([]byte, []int) {
	return file_ui_proto_rawDescGZIP(), []int{1}
}

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Time          string                 `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
	Connection    *Connection            `protobuf:"bytes,2,opt,name=connection,proto3" json:"connection,omitempty"`
	Rule          *Rule                  `protobuf:"bytes,3,opt,name=rule,proto3" json:"rule,omitempty"`
	Unixnano      int64                  `protobuf:"varint,4,opt,name=unixnano,proto3" json:"unixnano,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_ui_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_ui_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_ui_proto_rawDescGZIP(), []int{0}
}

func (x *Event) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

func (x *Event) GetConnection() *Connection {
	if x != nil {
		return x.Connection
	}
	return nil
}

func (x *Event) GetRule() *Rule {
	if x != nil {
		return x.Rule
	}
	return nil
}

func (x *Event) GetUnixnano() int64 {
	if x != nil {
		return x.Unixnano
	}
	return 0
}

type Statistics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DaemonVersion string                 `protobuf:"bytes,1,opt,name=daemon_version,json=daemonVersion,proto3" json:"daemon_version,omitempty"`
	Rules         uint64                 `protobuf:"varint,2,opt,name=rules,proto3" json:"rules,omitempty"`
	Uptime        uint64                 `protobuf:"varint,3,opt,name=uptime,proto3" json:"uptime,omitempty"`
	DnsResponses  uint64                 `protobuf:"varint,4,opt,name=dns_responses,json=dnsResponses,proto3" json:"dns_responses,omitempty"`
	Connections   uint64                 `protobuf:"varint,5,opt,name=connections,proto3" json:"connections,omitempty"`
	Ignored       uint64                 `protobuf:"varint,6,opt,name=ignored,proto3" json:"ignored,omitempty"`
	Accepted      uint64                 `protobuf:"varint,7,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Dropped       uint64                 `protobuf:"varint,8,opt,name=dropped,proto3" json:"dropped,omitempty"`
	RuleHits      uint64                 `protobuf:"varint,9,opt,name=rule_hits,json=ruleHits,proto3" json:"rule_hits,omitempty"`
	RuleMisses    uint64                 `protobuf:"varint,10,opt,name=rule_misses,json=ruleMisses,proto3" json:"rule_misses,omitempty"`
	ByProto       map[string]uint64      `protobuf:"bytes,11,rep,name=by_proto,json=byProto,proto3" json:"by_proto,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	ByAddress     map[string]uint64      `protobuf:"bytes,12,rep,name=by_address,json=byAddress,proto3" json:"by_address,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	ByHost        map[string]uint64      `protobuf:"bytes,13,rep,name=by_host,json=byHost,proto3" json:"by_host,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	ByPort        map[string]uint64      `protobuf:"bytes,14,rep,name=by_port,json=byPort,proto3" json:"by_port,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	ByUid         map[string]uint64      `protobuf:"bytes,15,rep,name=by_uid,json=byUid,proto3" json:"by_uid,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	ByExecutable  map[string]uint64      `protobuf:"bytes,16,rep,name=by_executable,json=byExecutable,proto3" json:"by_executable,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	Events        []*Event               `protobuf:"bytes,17,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Statistics) Reset() {
	*x = Statistics{}
	mi := &file_ui_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Statistics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Statistics) ProtoMessage() {}

func (x *Statistics) ProtoReflect() protoreflect.Message {
	mi := &file_ui_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Statistics.ProtoReflect.Descriptor instead.
func (*Statistics) Descriptor() ([]byte, []int) {
	return file_ui_proto_rawDescGZIP(), []int{1}
}

func (x *Statistics) GetDaemonVersion() string {
	if x != nil {
		return x.DaemonVersion
	}
	return ""
}

func (x *Statistics) GetRules() uint64 {
	if x != nil {
		return x.Rules
	}
	return 0
}

func (x *Statistics) GetUptime() uint64 {
	if x != nil {
		return x.Uptime
	}
	return 0
}

func (x *Statistics) GetDnsResponses() uint64 {
	if x != nil {
		return x.DnsResponses
	}
	return 0
}

func (x *Statistics) GetConnections() uint64 {
	if x != nil {
		return x.Connections
	}
	return 0
}

func (x *Statistics) GetIgnored() uint64 {
	if x != nil {
		return x.Ignored
	}
	return 0
}

func (x *Statistics) GetAccepted() uint64 {
	if x != nil {
		return x.Accepted
	}
	return 0
}

func (x *Statistics) GetDropped() uint64 {
	if x != nil {
		return x.Dropped
	}
	return 0
}

func (x *Statistics) GetRuleHits() uint64 {
	if x != nil {
		return x.RuleHits
	}
	return 0
}

func (x *Statistics) GetRuleMisses() uint64 {
	if x != nil {
		return x.RuleMisses
	}
	return 0
}

func (x *Statistics) GetByProto() map[string]uint64 {
	if x != nil {
		return x.ByProto
	}
	return nil
}

func (x *Statistics) GetByAddress() map[string]uint64 {
	if x != nil {
		return x.ByAddress
	}
	return nil
}

func (x *Statistics) GetByHost() map[string]uint64 {
	if x != nil {
		return x.ByHost
	}
	return nil
}

func (x *Statistics) GetByPort() map[string]uint64 {
	if x != nil {
		return x.ByPort
	}
	return nil
}

func (x *Statistics) GetByUid() map[string]uint64 {
	if x != nil {
		return x.ByUid
	}
	return nil
}

func (x *Statistics) GetByExecutable() map[string]uint64 {
	if x != nil {
		return x.ByExecutable
	}
	return nil
}

func (x *Statistics) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Stats         *Statistics            `protobuf:"bytes,2,opt,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_ui_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ui_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_ui_proto_rawDescGZIP(), []int{2}
}

func (x *PingRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PingRequest) GetStats() *Statistics {
	if x != nil {
		return x.Stats
	}
	return nil
}

type PingReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingReply) Reset() {
	*x = PingReply{}
	mi := &file_ui_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingReply) ProtoMessage() {}

func (x *PingReply) ProtoReflect() protoreflect.Message {
	mi := &file_ui_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingReply.ProtoReflect.Descriptor instead.
func (*PingReply) Descriptor() ([]byte, []int) {
	return file_ui_proto_rawDescGZIP(), []int{3}
}

func (x *PingReply) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type Connection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Protocol      string                 `protobuf:"bytes,1,opt,name=protocol,proto3" json:"protocol,omitempty"`
	SrcIp         string                 `protobuf:"bytes,2,opt,name=src_ip,json=srcIp,proto3" json:"src_ip,omitempty"`
	SrcPort       uint32                 `protobuf:"varint,3,opt,name=src_port,json=srcPort,proto3" json:"src_port,omitempty"`
	DstIp         string                 `protobuf:"bytes,4,opt,name=dst_ip,json=dstIp,proto3" json:"dst_ip,omitempty"`
	DstHost       string                 `protobuf:"bytes,5,opt,name=dst_host,json=dstHost,proto3" json:"dst_host,omitempty"`
	DstPort       uint32                 `protobuf:"varint,6,opt,name=dst_port,json=dstPort,proto3" json:"dst_port,omitempty"`
	UserId        uint32                 `protobuf:"varint,7,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProcessId     uint32                 `protobuf:"varint,8,opt,name=process_id,json=processId,proto3" json:"process_id,omitempty"`
	ProcessPath   string                 `protobuf:"bytes,9,opt,name=process_path,json=processPath,proto3" json:"process_path,omitempty"`
	ProcessCwd    string                 `protobuf:"bytes,10,opt,name=process_cwd,json=processCwd,proto3" json:"process_cwd,omitempty"`
	ProcessArgs   []string               `protobuf:"bytes,11,rep,name=process_args,json=processArgs,proto3" json:"process_args,omitempty"`
	ProcessEnv    map[string]string      `protobuf:"bytes,12,rep,name=process_env,json=processEnv,proto3" json:"process_env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Connection) Reset() {
	*x = Connection{}
	mi := &file_ui_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Connection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Connection) ProtoMessage() {}

func (x *Connection) ProtoReflect() protoreflect.Message {
	mi := &file_ui_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Connection.ProtoReflect.Descriptor instead.
func (*Connection) Descriptor() ([]byte, []int) {
	return file_ui_proto_rawDescGZIP(), []int{4}
}

func (x *Connection) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *Connection) GetSrcIp() string {
	if x != nil {
		return x.SrcIp
	}
	return ""
}

func (x *Connection) GetSrcPort() uint32 {
	if x != nil {
		return x.SrcPort
	}
	return 0
}

func (x *Connection) GetDstIp() string {
	if x != nil {
		return x.DstIp
	}
	return ""
}

func (x *Connection) GetDstHost() string {
	if x != nil {
		return x.DstHost
	}
	return ""
}

func (x *Connection) GetDstPort() uint32 {
	if x != nil {
		return x.DstPort
	}
	return 0
}

func (x *Connection) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Connection) GetProcessId() uint32 {
	if x != nil {
		return x.ProcessId
	}
	return 0
}

func (x *Connection) GetProcessPath() string {
	if x != nil {
		return x.ProcessPath
	}
	return ""
}

func (x *Connection) GetProcessCwd() string {
	if x != nil {
		return x.ProcessCwd
	}
	return ""
}

func (x *Connection) GetProcessArgs() []string {
	if x != nil {
		return x.ProcessArgs
	}
	return nil
}

func (x *Connection) GetProcessEnv() map[string]string {
	if x != nil {
		return x.ProcessEnv
	}
	return nil
}

type Operator struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Operand       string                 `protobuf:"bytes,2,opt,name=operand,proto3" json:"operand,omitempty"`
	Data          string                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Sensitive     bool                   `protobuf:"varint,4,opt,name=sensitive,proto3" json:"sensitive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Operator) Reset() {
	*x = Operator{}
	mi := &file_ui_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Operator) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Operator) ProtoMessage() {}

func (x *Operator) ProtoReflect() protoreflect.Message {
	mi := &file_ui_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Operator.ProtoReflect.Descriptor instead.
func (*Operator) Descriptor() ([]byte, []int) {
	return file_ui_proto_rawDescGZIP(), []int{5}
}

func (x *Operator) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Operator) GetOperand() string {
	if x != nil {
		return x.Operand
	}
	return ""
}

func (x *Operator) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *Operator) GetSensitive() bool {
	if x != nil {
		return x.Sensitive
	}
	return false
}

type Rule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Enabled       bool                   `protobuf:"varint,2,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Precedence    bool                   `protobuf:"varint,3,opt,name=precedence,proto3" json:"precedence,omitempty"`
	Action        string                 `protobuf:"bytes,4,opt,name=action,proto3" json:"action,omitempty"`
	Duration      string                 `protobuf:"bytes,5,opt,name=duration,proto3" json:"duration,omitempty"`
	Operator      *Operator              `protobuf:"bytes,6,opt,name=operator,proto3" json:"operator,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Rule) Reset() {
	*x = Rule{}
	mi := &file_ui_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rule) ProtoMessage() {}

func (x *Rule) ProtoReflect() protoreflect.Message {
	mi := &file_ui_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rule.ProtoReflect.Descriptor instead.
func (*Rule) Descriptor() ([]byte, []int) {
	return file_ui_proto_rawDescGZIP(), []int{6}
}

func (x *Rule) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Rule) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *Rule) GetPrecedence() bool {
	if x != nil {
		return x.Precedence
	}
	return false
}

func (x *Rule) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *Rule) GetDuration() string {
	if x != nil {
		return x.Duration
	}
	return ""
}

func (x *Rule) GetOperator() *Operator {
	if x != nil {
		return x.Operator
	}
	return nil
}

type ClientConfig struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name              string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Version           string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	IsFirewallRunning bool                   `protobuf:"varint,4,opt,name=isFirewallRunning,proto3" json:"isFirewallRunning,omitempty"`
	Config            string                 `protobuf:"bytes,5,opt,name=config,proto3" json:"config,omitempty"`
	LogLevel          uint32                 `protobuf:"varint,6,opt,name=logLevel,proto3" json:"logLevel,omitempty"`
	Rules             []*Rule                `protobuf:"bytes,7,rep,name=rules,proto3" json:"rules,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ClientConfig) Reset() {
	*x = ClientConfig{}
	mi := &file_ui_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientConfig) ProtoMessage() {}

func (x *ClientConfig) ProtoReflect() protoreflect.Message {
	mi := &file_ui_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientConfig.ProtoReflect.Descriptor instead.
func (*ClientConfig) Descriptor() ([]byte, []int) {
	return file_ui_proto_rawDescGZIP(), []int{7}
}

func (x *ClientConfig) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ClientConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ClientConfig) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ClientConfig) GetIsFirewallRunning() bool {
	if x != nil {
		return x.IsFirewallRunning
	}
	return false
}

func (x *ClientConfig) GetConfig() string {
	if x != nil {
		return x.Config
	}
	return ""
}

func (x *ClientConfig) GetLogLevel() uint32 {
	if x != nil {
		return x.LogLevel
	}
	return 0
}

func (x *ClientConfig) GetRules() []*Rule {
	if x != nil {
		return x.Rules
	}
	return nil
}

type Notification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ClientName    string                 `protobuf:"bytes,2,opt,name=clientName,proto3" json:"clientName,omitempty"`
	ServerName    string                 `protobuf:"bytes,3,opt,name=serverName,proto3" json:"serverName,omitempty"`
	Type          Action                 `protobuf:"varint,4,opt,name=type,proto3,enum=protocol.Action" json:"type,omitempty"`
	Data          string                 `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	Rules         []*Rule                `protobuf:"bytes,6,rep,name=rules,proto3" json:"rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Notification) Reset() {
	*x = Notification{}
	mi := &file_ui_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Notification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Notification) ProtoMessage() {}

func (x *Notification) ProtoReflect() protoreflect.Message {
	mi := &file_ui_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Notification.ProtoReflect.Descriptor instead.
func (*Notification) Descriptor() ([]byte, []int) {
	return file_ui_proto_rawDescGZIP(), []int{8}
}

func (x *Notification) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Notification) GetClientName() string {
	if x != nil {
		return x.ClientName
	}
	return ""
}

func (x *Notification) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

func (x *Notification) GetType() Action {
	if x != nil {
		return x.Type
	}
	return Action_NONE
}

func (x *Notification) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *Notification) GetRules() []*Rule {
	if x != nil {
		return x.Rules
	}
	return nil
}

type NotificationReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Code          NotificationReplyCode  `protobuf:"varint,2,opt,name=code,proto3,enum=protocol.NotificationReplyCode" json:"code,omitempty"`
	Data          string                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotificationReply) Reset() {
	*x = NotificationReply{}
	mi := &file_ui_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationReply) ProtoMessage() {}

func (x *NotificationReply) ProtoReflect() protoreflect.Message {
	mi := &file_ui_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationReply.ProtoReflect.Descriptor instead.
func (*NotificationReply) Descriptor() ([]byte, []int) {
	return file_ui_proto_rawDescGZIP(), []int{9}
}

func (x *NotificationReply) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *NotificationReply) GetCode() NotificationReplyCode {
	if x != nil {
		return x.Code
	}
	return NotificationReplyCode_OK
}

func (x *NotificationReply) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

var File_ui_proto protoreflect.FileDescriptor

const file_ui_proto_rawDesc = "" +
	"\n" +
	"\bui.proto\x12\bprotocol\"\x91\x01\n" +
	"\x05Event\x12\x12\n" +
	"\x04time\x18\x01 \x01(\tR\x04time\x124\n" +
	"\n" +
	"connection\x18\x02 \x01(\v2\x14.protocol.ConnectionR\n" +
	"connection\x12\"\n" +
	"\x04rule\x18\x03 \x01(\v2\x0e.protocol.RuleR\x04rule\x12\x1a\n" +
	"\bunixnano\x18\x04 \x01(\x03R\bunixnano\"\xc7\b\n" +
	"\n" +
	"Statistics\x12%\n" +
	"\x0edaemon_version\x18\x01 \x01(\tR\rdaemonVersion\x12\x14\n" +
	"\x05rules\x18\x02 \x01(\x04R\x05rules\x12\x16\n" +
	"\x06uptime\x18\x03 \x01(\x04R\x06uptime\x12#\n" +
	"\rdns_responses\x18\x04 \x01(\x04R\fdnsResponses\x12 \n" +
	"\vconnections\x18\x05 \x01(\x04R\vconnections\x12\x18\n" +
	"\aignored\x18\x06 \x01(\x04R\aignored\x12\x1a\n" +
	"\baccepted\x18\a \x01(\x04R\baccepted\x12\x18\n" +
	"\adropped\x18\b \x01(\x04R\adropped\x12\x1b\n" +
	"\trule_hits\x18\t \x01(\x04R\bruleHits\x12\x1f\n" +
	"\vrule_misses\x18\n" +
	" \x01(\x04R\n" +
	"ruleMisses\x12<\n" +
	"\bby_proto\x18\v \x03(\v2!.protocol.Statistics.ByProtoEntryR\abyProto\x12B\n" +
	"\n" +
	"by_address\x18\f \x03(\v2#.protocol.Statistics.ByAddressEntryR\tbyAddress\x129\n" +
	"\aby_host\x18\r \x03(\v2 .protocol.Statistics.ByHostEntryR\x06byHost\x129\n" +
	"\aby_port\x18\x0e \x03(\v2 .protocol.Statistics.ByPortEntryR\x06byPort\x126\n" +
	"\x06by_uid\x18\x0f \x03(\v2\x1f.protocol.Statistics.ByUidEntryR\x05byUid\x12K\n" +
	"\rby_executable\x18\x10 \x03(\v2&.protocol.Statistics.ByExecutableEntryR\fbyExecutable\x12'\n" +
	"\x06events\x18\x11 \x03(\v2\x0f.protocol.EventR\x06events\x1a:\n" +
	"\fByProtoEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x04R\x05value:\x028\x01\x1a<\n" +
	"\x0eByAddressEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x04R\x05value:\x028\x01\x1a9\n" +
	"\vByHostEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x04R\x05value:\x028\x01\x1a9\n" +
	"\vByPortEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x04R\x05value:\x028\x01\x1a8\n" +
	"\n" +
	"ByUidEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x04R\x05value:\x028\x01\x1a?\n" +
	"\x11ByExecutableEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x04R\x05value:\x028\x01\"I\n" +
	"\vPingRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12*\n" +
	"\x05stats\x18\x02 \x01(\v2\x14.protocol.StatisticsR\x05stats\"\x1b\n" +
	"\tPingReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"\xcc\x03\n" +
	"\n" +
	"Connection\x12\x1a\n" +
	"\bprotocol\x18\x01 \x01(\tR\bprotocol\x12\x15\n" +
	"\x06src_ip\x18\x02 \x01(\tR\x05srcIp\x12\x19\n" +
	"\bsrc_port\x18\x03 \x01(\rR\asrcPort\x12\x15\n" +
	"\x06dst_ip\x18\x04 \x01(\tR\x05dstIp\x12\x19\n" +
	"\bdst_host\x18\x05 \x01(\tR\adstHost\x12\x19\n" +
	"\bdst_port\x18\x06 \x01(\rR\adstPort\x12\x17\n" +
	"\auser_id\x18\a \x01(\rR\x06userId\x12\x1d\n" +
	"\n" +
	"process_id\x18\b \x01(\rR\tprocessId\x12!\n" +
	"\fprocess_path\x18\t \x01(\tR\vprocessPath\x12\x1f\n" +
	"\vprocess_cwd\x18\n" +
	" \x01(\tR\n" +
	"processCwd\x12!\n" +
	"\fprocess_args\x18\v \x03(\tR\vprocessArgs\x12E\n" +
	"\vprocess_env\x18\f \x03(\v2$.protocol.Connection.ProcessEnvEntryR\n" +
	"processEnv\x1a=\n" +
	"\x0fProcessEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"j\n" +
	"\bOperator\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x18\n" +
	"\aoperand\x18\x02 \x01(\tR\aoperand\x12\x12\n" +
	"\x04data\x18\x03 \x01(\tR\x04data\x12\x1c\n" +
	"\tsensitive\x18\x04 \x01(\bR\tsensitive\"\xb8\x01\n" +
	"\x04Rule\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aenabled\x18\x02 \x01(\bR\aenabled\x12\x1e\n" +
	"\n" +
	"precedence\x18\x03 \x01(\bR\n" +
	"precedence\x12\x16\n" +
	"\x06action\x18\x04 \x01(\tR\x06action\x12\x1a\n" +
	"\bduration\x18\x05 \x01(\tR\bduration\x12.\n" +
	"\boperator\x18\x06 \x01(\v2\x12.protocol.OperatorR\boperator\"\xd4\x01\n" +
	"\fClientConfig\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12,\n" +
	"\x11isFirewallRunning\x18\x04 \x01(\bR\x11isFirewallRunning\x12\x16\n" +
	"\x06config\x18\x05 \x01(\tR\x06config\x12\x1a\n" +
	"\blogLevel\x18\x06 \x01(\rR\blogLevel\x12$\n" +
	"\x05rules\x18\a \x03(\v2\x0e.protocol.RuleR\x05rules\"\xbe\x01\n" +
	"\fNotification\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1e\n" +
	"\n" +
	"clientName\x18\x02 \x01(\tR\n" +
	"clientName\x12\x1e\n" +
	"\n" +
	"serverName\x18\x03 \x01(\tR\n" +
	"serverName\x12$\n" +
	"\x04type\x18\x04 \x01(\x0e2\x10.protocol.ActionR\x04type\x12\x12\n" +
	"\x04data\x18\x05 \x01(\tR\x04data\x12$\n" +
	"\x05rules\x18\x06 \x03(\v2\x0e.protocol.RuleR\x05rules\"l\n" +
	"\x11NotificationReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x123\n" +
	"\x04code\x18\x02 \x01(\x0e2\x1f.protocol.NotificationReplyCodeR\x04code\x12\x12\n" +
	"\x04data\x18\x03 \x01(\tR\x04data*\xda\x01\n" +
	"\x06Action\x12\b\n" +
	"\x04NONE\x10\x00\x12\x11\n" +
	"\rLOAD_FIREWALL\x10\x01\x12\x13\n" +
	"\x0fUNLOAD_FIREWALL\x10\x02\x12\x11\n" +
	"\rCHANGE_CONFIG\x10\x03\x12\x0f\n" +
	"\vENABLE_RULE\x10\x04\x12\x10\n" +
	"\fDISABLE_RULE\x10\x05\x12\x0f\n" +
	"\vDELETE_RULE\x10\x06\x12\x0f\n" +
	"\vCHANGE_RULE\x10\a\x12\r\n" +
	"\tLOG_LEVEL\x10\b\x12\b\n" +
	"\x04STOP\x10\t\x12\x13\n" +
	"\x0fMONITOR_PROCESS\x10\n" +
	"\x12\x18\n" +
	"\x14STOP_MONITOR_PROCESS\x10\v**\n" +
	"\x15NotificationReplyCode\x12\x06\n" +
	"\x02OK\x10\x00\x12\t\n" +
	"\x05ERROR\x10\x012\xf8\x01\n" +
	"\x02UI\x124\n" +
	"\x04Ping\x12\x15.protocol.PingRequest\x1a\x13.protocol.PingReply\"\x00\x121\n" +
	"\aAskRule\x12\x14.protocol.Connection\x1a\x0e.protocol.Rule\"\x00\x12=\n" +
	"\tSubscribe\x12\x16.protocol.ClientConfig\x1a\x16.protocol.ClientConfig\"\x00\x12J\n" +
	"\rNotifications\x12\x1b.protocol.NotificationReply\x1a\x16.protocol.Notification\"\x00(\x010\x01B6Z4github.com/penguinpowernz/gosnitch/internal/protocolb\x06proto3"

var (
	file_ui_proto_rawDescOnce sync.Once
	file_ui_proto_rawDescData []byte
)

func file_ui_proto_rawDescGZIP() []byte {
	file_ui_proto_rawDescOnce.Do(func() {
		file_ui_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ui_proto_rawDesc), len(file_ui_proto_rawDesc)))
	})
	return file_ui_proto_rawDescData
}

var file_ui_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_ui_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_ui_proto_goTypes = []any{
	(Action)(0),                // 0: protocol.Action
	(NotificationReplyCode)(0), // 1: protocol.NotificationReplyCode
	(*Event)(nil),              // 2: protocol.Event
	(*Statistics)(nil),         // 3: protocol.Statistics
	(*PingRequest)(nil),        // 4: protocol.PingRequest
	(*PingReply)(nil),          // 5: protocol.PingReply
	(*Connection)(nil),         // 6: protocol.Connection
	(*Operator)(nil),           // 7: protocol.Operator
	(*Rule)(nil),               // 8: protocol.Rule
	(*ClientConfig)(nil),       // 9: protocol.ClientConfig
	(*Notification)(nil),       // 10: protocol.Notification
	(*NotificationReply)(nil),  // 11: protocol.NotificationReply
	nil,                        // 12: protocol.Statistics.ByProtoEntry
	nil,                        // 13: protocol.Statistics.ByAddressEntry
	nil,                        // 14: protocol.Statistics.ByHostEntry
	nil,                        // 15: protocol.Statistics.ByPortEntry
	nil,                        // 16: protocol.Statistics.ByUidEntry
	nil,                        // 17: protocol.Statistics.ByExecutableEntry
	nil,                        // 18: protocol.Connection.ProcessEnvEntry
}
var file_ui_proto_depIdxs = []int32{
	6,  // 0: protocol.Event.connection:type_name -> protocol.Connection
	8,  // 1: protocol.Event.rule:type_name -> protocol.Rule
	12, // 2: protocol.Statistics.by_proto:type_name -> protocol.Statistics.ByProtoEntry
	13, // 3: protocol.Statistics.by_address:type_name -> protocol.Statistics.ByAddressEntry
	14, // 4: protocol.Statistics.by_host:type_name -> protocol.Statistics.ByHostEntry
	15, // 5: protocol.Statistics.by_port:type_name -> protocol.Statistics.ByPortEntry
	16, // 6: protocol.Statistics.by_uid:type_name -> protocol.Statistics.ByUidEntry
	17, // 7: protocol.Statistics.by_executable:type_name -> protocol.Statistics.ByExecutableEntry
	2,  // 8: protocol.Statistics.events:type_name -> protocol.Event
	3,  // 9: protocol.PingRequest.stats:type_name -> protocol.Statistics
	18, // 10: protocol.Connection.process_env:type_name -> protocol.Connection.ProcessEnvEntry
	7,  // 11: protocol.Rule.operator:type_name -> protocol.Operator
	8,  // 12: protocol.ClientConfig.rules:type_name -> protocol.Rule
	0,  // 13: protocol.Notification.type:type_name -> protocol.Action
	8,  // 14: protocol.Notification.rules:type_name -> protocol.Rule
	1,  // 15: protocol.NotificationReply.code:type_name -> protocol.NotificationReplyCode
	4,  // 16: protocol.UI.Ping:input_type -> protocol.PingRequest
	6,  // 17: protocol.UI.AskRule:input_type -> protocol.Connection
	9,  // 18: protocol.UI.Subscribe:input_type -> protocol.ClientConfig
	11, // 19: protocol.UI.Notifications:input_type -> protocol.NotificationReply
	5,  // 20: protocol.UI.Ping:output_type -> protocol.PingReply
	8,  // 21: protocol.UI.AskRule:output_type -> protocol.Rule
	9,  // 22: protocol.UI.Subscribe:output_type -> protocol.ClientConfig
	10, // 23: protocol.UI.Notifications:output_type -> protocol.Notification
	20, // [20:24] is the sub-list for method output_type
	16, // [16:20] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_ui_proto_init() }
func file_ui_proto_init() {
	if File_ui_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ui_proto_rawDesc), len(file_ui_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ui_proto_goTypes,
		DependencyIndexes: file_ui_proto_depIdxs,
		EnumInfos:         file_ui_proto_enumTypes,
		MessageInfos:      file_ui_proto_msgTypes,
	}.Build()
	File_ui_proto = out.File
	file_ui_proto_goTypes = nil
	file_ui_proto_depIdxs = nil
}
